### ISSUE TITLE
import javax.sound.

### ISSUE THREAD

**Issue by yongjiliu** [v4lk/lwbd#1]
How can i import javax.sound.\* in android? Thank you

**Comment by qlyoung** [comment]
You can't. Android does not support the Java Sound API.

If you're trying to use this on Android, note that FLAC is not yet supported for Android because the FLAC decoder I use currently requires javax.sound.sampled. You will need to remove the FLAC parts from the source. I've been meaning to move the non-Android parts to a separate branch; I may get to that today.

If you look here, you will see that javax.sound is missing.
http://developer.android.com/reference/packages.html

**Comment by yongjiliu** [comment]
understood,I am looking forward to android branch, thank you!!

**Comment by HBiSoft** [comment]
@qlyoung No branch yet?

**Comment by HBiSoft** [comment]
@qlyoung Can you please create a branch for android, all the questions/issues on this library is about android. I have been searching for something like this that can run on android and I couldn't find anything.

**Comment by qlyoung** [comment]
No, apparently I didn't get to it 3 years ago. I am not actively maintaining this library. I suggest that you manually patch out the FLAC portions. I think if you delete `lwbd/src/v4lk/lwbd/decoders/processing/jflac`, and everything that depends on (which should just be `JFlacDecoder.java`) you'll have a version compatible with Android.

I've shipped this library in an Android app before, but I sucked at programming at that time and included it in the repo as a built jar instead of a git submodule or something :/

https://github.com/qlyoung/lowlatency/blob/master/Main/libs/lwbd.jar

If you get it working please let me know!

@HBiSoft

**Comment by HBiSoft** [comment]
@qlyoung 

Ok I got it working on Android, unfortunately I can't use this for what I wanted to. I was hoping that I can use the "`Energy`" to calculate the BPM (Beats Per Minute), but the  "`Energy`" is inconsistent. Here is what I get in my log when using a small `.mp3` file

```
I/Time:: 0.162s
I/Energy :: 0.19886135
I/Time:: 0.185s
I/Energy :: 0.108002
I/Time:: 0.417s
I/Energy :: 0.2309263
I/Time:: 0.603s
I/Energy :: 0.17462657
I/Time:: 0.766s
I/Energy :: 0.024711052
I/Time:: 0.812s
I/Energy :: 0.24250112
I/Time:: 1.021s
I/Energy :: 0.24106568
I/Time:: 1.184s
I/Energy :: 0.06421423
I/Time:: 1.23s
I/Energy :: 0.24013229
I/Time:: 1.462s
I/Energy :: 0.18630652
I/Time:: 1.602s
I/Energy :: 0.08581823
I/Time:: 1.648s
I/Energy :: 0.194149
I/Time:: 1.857s
I/Energy :: 0.31209955
I/Time:: 2.02s
I/Energy :: 0.07896435
I/Time:: 2.066s
I/Energy :: 0.15071605
I/Time:: 2.275s
I/Energy :: 0.35122392
I/Time:: 2.438s
I/Energy :: 0.16268717
I/Time:: 2.484s
I/Energy :: 0.23393154
```

I can imagine this will be helpful for someone that, for example, want's to change the color of something depending on the intensity of the sound that is being played.

But like I mentioned it is not very consistent, so I wouldn't rely on this for precision calculations.

**Comment by qlyoung** [comment]
@HBiSoft 

How do you suppose BPM detectors work, if not on sound energy? If you want BPM detection you need to apply a basic understanding of statistics and periodic functions to the data you get here. It is perfectly possible to extract BPM from this information - you just need to apply yourself.

Said another way - this library is not a BPM detector, it's a beat detector. Process the information it gives to you and you'll get BPM.

>But like I mentioned it is not very consistent, I wouldn't rely on this for precision calculations.

You are free to rely on whatever library you like for "precision calculations", but that statement suggests to me a basic misunderstanding of the techniques and algorithms used in this domain.

If you want to learn about sound energy, beat detection and BPM detection I suggest you read through the following basic resources:

* https://en.wikipedia.org/wiki/Beat_detection
* http://www.flipcode.com/misc/BeatDetectionAlgorithms.pdf
* https://sound.stackexchange.com/questions/27460/how-do-software-algorithms-to-calculate-bpm-usually-work

And finally, if you decide to improve the library - I take pull requests :)

**Comment by HBiSoft** [comment]
@qlyoung

Sorry, I read my previous comment and realized I couldn't chosen my word's better. It wasn't my intention to criticize your work.

Thank you for the link's, I will definitely have a look.

I found a library `SoundTouch` that does exactly what I want.

Thank you for replying.

Regards.

**Comment by qlyoung** [comment]
Excellent, good luck with your project.
